### ISSUE TITLE
rpm spec.in fails to build (v3.6.0) with target noarch since web fronted was splitted out of the main archive. (easy to fix)

### ISSUE THREAD

**Issue by olahaye74** [ganglia/monitor-core#110]
- /usr/bin/make -C web
  make: **\* web: No such file or directory.  Stop.

IMHO, all "%ifarch noarch" needs to be removed.

**Comment by mknawabi** [comment]
This still fails for me with ganglia-3.6.1.tar.gz--what is the supposed easy fix? I have tried removing the web inferences in the spec file but still get a failed build.

Thank you,

-Yama
