### ISSUE TITLE
add supported for ganglia monitoring process, with information such as, CPU, memory, hard disk, network usage rate.

### ISSUE THREAD

**Issue by hackereye** [ganglia/monitor-core#125]
add supported for ganglia monitoring process, with information such as, CPU, memory, hard disk, network usage rate.

**Comment by hawson** [comment]
All of those metrics are currently supported by gmod, and have been for years.  If there's something specific missing you'd like to see, please consider doing one of the following:

1. Submit a new issue with the details for the specific metric
1. Write a plugin for the new metric (and consider publishing it!)  See http://ganglia.info/?p=277
1. Fork the code and submit a pull request
