### ISSUE TITLE
diskfree module doesn't report on disks smaller than 1GB

### ISSUE THREAD

**Issue by blakecrosby** [ganglia/monitor-core#193]
Would it be possible to make the MIN_DISK_SIZE (https://github.com/ganglia/monitor-core/blob/9c4a7dbdc8da547018f01ffa38da379b033f7409/gmond/python_modules/disk/diskfree.py#L32) configurable?

This way we can monitor disks that are smaller (or larger) than the default of 1GB :)

**Comment by vvuksan** [comment]
Addressed by this commit

https://github.com/ganglia/monitor-core/commit/b168245d7e5b9f027a2b2154773816e8a5f99eb4
