### ISSUE TITLE
Compiling with riemann support failed

### ISSUE THREAD

**Issue by qnick** [ganglia/monitor-core#239]
Cannot compile ganglia with riemann support following [these instructions](https://github.com/ganglia/monitor-core/wiki/Riemann-Integration).
What I do:
```bash
wget http://downloads.sourceforge.net/project/ganglia/ganglia%20monitoring%20core/3.7.2/ganglia-3.7.2.tar.gz
tar xzf ganglia-3.7.2.tar.gz && cd ganglia-3.7.2
# compiler cannot find riemann.pb-c.h in /usr/include/riemann/proto/ , so I just copy it to default "include" directory
cp /usr/include/riemann/proto/riemann.pb-c.h include/

# there is no 'bootstrap' file , so I pass the "./bootstrap" step
./configure --with-gmetad --with-riemann
make
```
What I got:
```
make[2]: *** No rule to make target `riemann.pb-c.o', needed by `gmetad'.  Stop.
```

**Comment by vvuksan** [comment]
@satterly Can you help ? I believe we removed riemann.pb-c files which may have been short sighted :-/

**Comment by vvuksan** [comment]
Hi @qnick,

Can you download this file

wget https://raw.githubusercontent.com/satterly/monitor-core/ee613f1261ae52b0fc305358e3dd6edee3c609ad/gmetad/riemann.proto

and put it inside gmetad/ directory then rerun configure. Also make sure you have

protobuf-c-compiler

installed. Let me know if that fixes the issue. Thanks.

**Comment by satterly** [comment]
Riemann integration still works out-of-the-box. I just tested Ganglia master branch in on my "ganglia dev" environment which is a Ubuntu 14.04 LTS vagrant box without a problem.

Try it for yourself [here](https://github.com/satterly/vagrants/tree/master/ganglia-dev) by cloning my Vagrants repo and running `cd ganglia-dev && vagrant up trusty`.

The only settings I made to `gmetad.conf` were:
```
riemann_server "localhost"
riemann_attributes "customer=Acme Corp,environment=PROD"
write_rrds off
```

And an example of a Ganglia metric sent to Riemann with this config is...
```
#riemann.codec.Event{:host "vagrant-ubuntu-trusty-64", :service "gexec", :state "warning", :description "gexec is OFF", :metric nil, :tags nil, :time 1.447368679678E9, :ttl 300.0, :environment "PROD", :customer "Acme Corp", :location "unspecified", :ip "10.0.2.15", :cluster "unspecified", :grid "unspecified"}
```
@qnick, if you try all of that and still have problems let us know.
