### ISSUE TITLE
Make Failed with SunOS 5.10 

### ISSUE THREAD

**Issue by riboseyim** [ganglia/monitor-core#272]
OS version : SunOS  Generic_139555-08 sun4v 

**Ganglia-3.7.2** 

**./configure is Works. Make Failed:**

`In file included from /usr/local/lib/gcc-lib/sparc-sun-solaris2.10/3.3.2/include/sys/types.h:27,
                 from update_pidfile.c:5:
/usr/include/sys/feature_tests.h:332:2:
#error "Compiler or options invalid for pre-UNIX 03 X/Open applications and pre-2001 POSIX applications"
make[2]: *** [update_pidfile.lo] Error 1
make[2]: Leaving directory `/slview/install/ganglia-3.7.2/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/slview/install/ganglia-3.7.2'
make: *** [all] Error 2`

**Comment by afbjorklund** [comment]
Is this the same issue as #38 ?

**Comment by riboseyim** [comment]
It's Works!

Thank you!
